import type { ClientProfile } from "./types";

// Mirrors backend/examples/sample_clients.json — kept in the frontend so the
// intake form can offer one-click "Load Example" buttons without a round trip.
export const SAMPLE_CLIENTS: { label: string; profile: ClientProfile }[] = [
  {
    label: "Harborline Restaurant Group",
    profile: {
      company_name: "Harborline Restaurant Group",
      industry: "Restaurants & Hospitality",
      annual_revenue: 18500000,
      employee_count: 340,
      number_of_locations: 12,
      current_banking_products: ["Business Checking", "Merchant Services"],
      current_pain_points: [
        "Managers spend hours each week making branch deposits",
        "No visibility into cash position across all 12 locations",
        "Recent counterfeit bill incident at two locations",
      ],
      erp_system: "QuickBooks Enterprise",
      current_payment_methods: ["Cash", "Credit Card", "Check"],
      monthly_ach_volume: 45000,
      monthly_wire_volume: 0,
      monthly_check_volume: 120000,
      monthly_cash_deposits: 680000,
      fraud_history: "Minor Incident",
      growth_plans: "Opening 4 new locations in the next 18 months across two new states.",
    },
  },
  {
    label: "Northgate Manufacturing Co.",
    profile: {
      company_name: "Northgate Manufacturing Co.",
      industry: "Industrial Manufacturing",
      annual_revenue: 62000000,
      employee_count: 410,
      number_of_locations: 3,
      current_banking_products: ["Business Checking", "Line of Credit"],
      current_pain_points: [
        "Lost $85,000 to check fraud last year",
        "AP team manually cuts over 200 checks per month",
        "Excess cash sits idle in checking earning nothing",
      ],
      erp_system: "SAP Business One",
      current_payment_methods: ["Check", "Wire", "ACH"],
      monthly_ach_volume: 310000,
      monthly_wire_volume: 450000,
      monthly_check_volume: 890000,
      monthly_cash_deposits: 0,
      fraud_history: "Significant Loss",
      growth_plans: "Evaluating acquisition of a regional competitor within 12 months.",
    },
  },
  {
    label: "Pinnacle Cloud Software",
    profile: {
      company_name: "Pinnacle Cloud Software",
      industry: "SaaS / Technology",
      annual_revenue: 9200000,
      employee_count: 65,
      number_of_locations: 1,
      current_banking_products: ["Business Checking"],
      current_pain_points: [
        "Customer invoices are paid late via mailed checks",
        "Payroll is run manually through the bank's teller line",
        "No treasury reporting integration with NetSuite",
      ],
      erp_system: "NetSuite",
      current_payment_methods: ["Credit Card", "ACH"],
      monthly_ach_volume: 210000,
      monthly_wire_volume: 15000,
      monthly_check_volume: 8000,
      monthly_cash_deposits: 0,
      fraud_history: "None",
      growth_plans: "Raised a $20M Series B; plans to double headcount and expand into EU market in 24 months.",
    },
  },
  {
    label: "Meridian Health Partners",
    profile: {
      company_name: "Meridian Health Partners",
      industry: "Healthcare Services",
      annual_revenue: 34000000,
      employee_count: 275,
      number_of_locations: 7,
      current_banking_products: ["Business Checking", "Business Savings"],
      current_pain_points: [
        "Insurance reimbursement checks pile up before being deposited",
        "Multiple clinics each managing their own banking relationship",
        "Payroll across 7 locations is a manual, error-prone process",
      ],
      erp_system: "Sage Intacct",
      current_payment_methods: ["Check", "ACH"],
      monthly_ach_volume: 180000,
      monthly_wire_volume: 0,
      monthly_check_volume: 260000,
      monthly_cash_deposits: 12000,
      fraud_history: "None",
      growth_plans: "Consolidating clinic administration and considering 2-3 tuck-in acquisitions.",
    },
  },
];
